### ISSUE TITLE
Create UML Diagrams

### ISSUE THREAD

**Issue by haard19** [nguyensjsu/sp22-202-code-brewers#18]
Includes class diagram as well as component diagram.

**Comment by ronak0001** [comment]
https://github.com/nguyensjsu/sp22-202-code-brewers/blob/main/images/dodgeCarComponentDiagram.png
https://github.com/nguyensjsu/sp22-202-code-brewers/blob/main/images/ClassDiagram.png
https://github.com/nguyensjsu/sp22-202-code-brewers/blob/main/images/CommandDesignPattern.png
https://github.com/nguyensjsu/sp22-202-code-brewers/blob/main/images/DecoratorDesignPattern.png
https://github.com/nguyensjsu/sp22-202-code-brewers/blob/main/images/SingletonDesignPattern.png
https://github.com/nguyensjsu/sp22-202-code-brewers/blob/main/images/StateDesignPattern.png
https://github.com/nguyensjsu/sp22-202-code-brewers/blob/main/images/StrategyDesignPattern.png
